export const GET_RECIPES = "GET_RECIPES";
export const ADD_RECIPE = "ADD_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE";
export const UPDATE_RECIPE = "UPDATE_RECIPE";

export const SET_ACTIVE_RECIPE = "SET_ACTIVE_RECIPE";

export const SET_ACTIVE_VERSION = "SET_ACTIVE_VERSION";
export const DELETE_VERSION = "DELETE_VERSION";